### ISSUE TITLE
Function Names

### ISSUE THREAD

**Issue by Jnetops** [xiaokanghub/Arena_of_Valor#2]
Do you know the method names that do the encryption and or the actual udp connection? Researching myself would be great to get a bit of info.

**Comment by xiaokanghub** [comment]
> Do you know the method names that do the encryption and or the actual udp connection? Researching myself would be great to get a bit of info.

Hmmm, u can hook the sendto func by Frida and print the backtrace, then u can get the encryption func. 
```
const f = Module.getExportByName('libc.so', 'sendto');
Interceptor.attach(f, {
  onEnter(args) {
    console.log('sendto called from:\n' +
        Thread.backtrace(this.context, Backtracer.ACCURATE)
        .map(DebugSymbol.fromAddress).join('\n') + '\n');
  }
});
```

**Comment by Jnetops** [comment]
Is it happening in native or emulated? I went through the effort of getting access under the hood to il2cpp's imported dll's. I see all the opcodes and their respective CSPkg packing and unpacking and the zlib library that appears to compress things. I also found the tgcpapi piece that I thought was doing the encrypting but maybe not? Dunno. Did you have to get access to the side loaded dll's at all or do it all in native mode?

**Comment by Jnetops** [comment]
backtracing the way you described I end up at "boot.oat!0x8fbcf"

**Comment by xiaokanghub** [comment]
> Is it happening in native or emulated? I went through the effort of getting access under the hood to il2cpp's imported dll's. I see all the opcodes and their respective CSPkg packing and unpacking and the zlib library that appears to compress things. I also found the tgcpapi piece that I thought was doing the encrypting but maybe not? Dunno. Did you have to get access to the side loaded dll's at all or do it all in native mode?

tgcpapi_taes_encrypt -> libapollo.so

**Comment by Jnetops** [comment]
Have you had success getting useful data from that crypt function? I've already been hooking it but the data is def not the root of traffic. It's clear it's using tcp tls primarily for communication and it appears okhttp might be what is being used but not sure? From what I've seen in the il2cpp side it appears all opcodes pack data and at some point bridge that data back over to regular so libraries and are sent. Though I could be wrong I haven't found the functions that generate https traffic from within the dlls loaded into memory.

**Comment by xiaokanghub** [comment]
> Have you had success getting useful data from that crypt function? I've already been hooking it but the data is def not the root of traffic. It's clear it's using tcp tls primarily for communication and it appears okhttp might be what is being used but not sure? From what I've seen in the il2cpp side it appears all opcodes pack data and at some point bridge that data back over to regular so libraries and are sent. Though I could be wrong I haven't found the functions that generate https traffic from within the dlls loaded into memory.

What's the useful data of do you want?

**Comment by Jnetops** [comment]
game data ofc. You doing things in game. Looks like you are getting the data, based on those packets you got in ur script. Same stuff coming my way in wireshark. Not tls, just tcp from the looks of it.

**Comment by xiaokanghub** [comment]
> game data ofc. You doing things in game. Looks like you are getting the data, based on those packets you got in ur script. Same stuff coming my way in wireshark. Not tls, just tcp from the looks of it.

Did u get the data what's like the "33 66 00 0b 00" from tcp?

**Comment by Jnetops** [comment]
Yep, that's what i'm seeing in wireshark. The uncompressed data that your script outputs looks a lot like the stuff getting written to the the tdrwritebuffer and then compressed with l4z which I can see inside il2cpp stuff. Looks like I got the right data already, was just looking at things wrong. Thanks again.

**Comment by Jnetops** [comment]
You do game hacking? If so wanna chat on discord?

**Comment by xiaokanghub** [comment]
> You do game hacking? If so wanna chat on discord?

xiaokang#4021

**Comment by Jnetops** [comment]
Added you

**Comment by innocentvoice** [comment]
Hi, i wanted to discuss with you about the python script, would you mind if i wanted to add your discord account

**Comment by xiaokanghub** [comment]
> Hi, i wanted to discuss with you about the python script, would you mind if i wanted to add your discord account

we can talk about  that in here

**Comment by innocentvoice** [comment]
> > Hi, i wanted to discuss with you about the python script, would you mind if i wanted to add your discord account
> 
> we can talk about that in here

i wonder, the character files itself is packed in a .pkg.bytes file, although it's just a normal zip, but when i unpacked it, it seems all the xml files have been encrypted (I'm thinking it's XOR encryption), do you know any way to decrypt it

**Comment by xiaokanghub** [comment]
> > > Hi, i wanted to discuss with you about the python script, would you mind if i wanted to add your discord account
> > 
> > 
> > we can talk about that in here
> 
> i wonder, the character files itself is packed in a .pkg.bytes file, although it's just a normal zip, but when i unpacked it, it seems all the xml files have been encrypted (I'm thinking it's XOR encryption), do you know any way to decrypt it

u need to analyse the application and find the decryption func
